- hosts: masters
  become: yes
  vars:
    # kubernetes_installed : '1'
  tasks:
    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none
    - name: Disable swap
      command: swapoff -a
      # when: kubernetes_installed > 0
    # The first task initializes the cluster by running kubeadm init.
    # Passing the argument --pod-network-cidr=192.168.0.0/16 specifies the private subnet that the pod IPs will be assigned from.
    # Flannel uses the above subnet by default; we're telling kubeadm to use the same subnet.
    - name: initialize the cluster
      # shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> /home/vagrant/cluster_initialized.txt
      command: kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10"  --node-name k8s-master01 --pod-network-cidr=192.168.0.0/16
      args:
        # chdir: $HOME
        chdir: /home/vagrant
        creates: cluster_initialized.txt
    # creates a .kube directory at /home/ubuntu. This directory will hold configuration information such as
    # the admin key files, which are required to connect to the cluster, and the cluster's API address.
    - name: create .kube directory
      become: yes
      become_user: vagrant
      file:
        # path: $HOME/.kube
        path: /home/vagrant/.kube
        state: directory
        mode: 0755
    # copies the /etc/kubernetes/admin.conf file that was generated from kubeadm init
    # to your non-root user's home directory.This will allow you to use kubectl
    # to access the newly-created cluster.
    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
    # runs kubectl apply to install Flannel.kubectl to create the objects described in the descriptor.[yml|json] file.
    # The kube-flannel.yml file contains the descriptions of objects required for setting up Flannel in the cluster.
    - name: "Install flannel pod network"
      become: yes
      become_user: vagrant
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> /home/vagrant/pod_network_setup.txt
      args:
        # chdir: $HOME
        chdir: /home/vagrant
        creates: pod_network_setup.txt
