---
- hosts: masters
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: initialize the cluster
      # shell: kubeadm init --cri-socket /run/containerd/containerd.sock --apiserver-advertise-address="10.217.50.10" --apiserver-cert-extra-sans="10.217.50.10"  --node-name vagrant-k8s-master02 --pod-network-cidr=10.217.0.0/16 >> cluster_initialized.txt
      shell: kubeadm init --cri-socket /run/containerd/containerd.sock --apiserver-advertise-address="10.217.50.10" --apiserver-cert-extra-sans="10.217.50.10"  --node-name vagrant-k8s-master02 --pod-network-cidr=10.217.0.0/16>> cluster_initialized.txt
      args:
        chdir: /home/vagrant
        creates: cluster_initialized.txt
    - name: create .kube directory
      become_user: vagrant
      file:
        path: /home/vagrant/.kube
        state: directory
        mode: 0755
    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        group: vagrant
    - name: "Install cilium pod network"
      become_user: vagrant
      # shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/62e44c867a2846fefb68bd5f178daf4da3095ccb/Documentation/kube-flannel.yml >> pod_network_setup.txt
      # shell: kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.5/examples/kubernetes/1.14/cilium.yaml >> pod_network_setup.txt
      shell: kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml >> pod_network_setup.txt
      args:
        chdir: /home/vagrant
        creates: pod_network_setup.txt
