- hosts: masters
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none
    - name: Disable swap
      command: swapoff -a
    - name: join cluster
      shell: "{{ hostvars['vagrant-k8s-master02'].join_command }} >> node_joined.txt"
      args:
        chdir: /home/vagrant
        creates: node_joined.txt
