---
- name: Remove swapfile from /etc/fstab
  mount:
   name: "{{ item }}"
   fstype: swap
   state: absent
  with_items:
   - swap
   - none
- name: Disable swap
  command: swapoff -a
- name: "Load br_netfilter kernel module"
  modprobe:
    name: br_netfilter
    state: present
- name: "Set bridge-nf-call-iptables"
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
- name: "Set ip_forward"
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
- name: "Add gpg key (Ubuntu)"
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: "Add kubernetes source list (Ubuntu)"
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-{{ distribution_release }} main"
    state: present
    filename: "kubernetes"
- name: "Update the repository cache (Ubuntu)"
  apt:
    update_cache: yes
- name: "Install kubelet, kubectl, kubeadm"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - 'kubelet={{ kubernetes_version }}'
    - 'kubectl={{ kubernetes_version }}'
    - 'kubeadm={{ kubernetes_version }}'
