---
    # - name: Contains tasks variables for installer

    - name: Contains tasks bootstrap components for debian systems
      include_tasks: tasks/bootstrap_containerd.yml
      when: " ansible_os_family == 'Debian' and ansible_distribution in ['Debian','Ubuntu'] "

    - name: Contains tasks kubernetes component installation for debian systems
      include_tasks: tasks/k8s_debian.yml
      when: " ansible_os_family == 'Debian' and ansible_distribution in ['Debian','Ubuntu'] "

    - name: Contains tasks kubernetes component installation for debian systems
      include_tasks: tasks/containerd.yml
      when: " ansible_os_family == 'Debian' and ansible_distribution in ['Debian','Ubuntu'] "

    - name: Contains tasks bootstrap components for redhat systems
      include_tasks: tasks/bootstrap_containerd.yml
      when: " ansible_os_family == 'RedHat' and ansible_distribution in ['CentOS','Fedora','Scientific'] "

    - name: Contains tasks kubernetes component installation for redhat systems
      include_tasks: tasks/k8s_redhat.yaml
      when: " ansible_os_family == 'RedHat' and ansible_distribution in ['CentOS','Fedora','Scientific'] "
